package gm;

public class Point {
	// This code was generated by a tool. 
	private int x;
	private int y;
	private int state;

	Point(int xt, int yt, int statet) {
		x = xt;
		y = yt;
		state = statet;
	}

	public boolean equalsPosition(Point q) {
		return x==q.x && y==q.y;
	}
	
	public void setX(int x) {
		this.x = x;
	}
	
	public void setY(int y) {
		this.y = y;
	}

	public void setState(int player) {
		state = player;
	}
	
	public int getX() {
		return this.x;
	}
	
	public int getY() {
		return this.y;
	}

	public int getState() {
		return state;
	}
	
	public String toString() {
		return x + "," + y + "|" + state;
	}
	
}
