package gm;

/**
 * 
 * @author Angelos Trigkas
 * 
 * Class Point implements a point inside the board.
 */
public class Point {
	// This code was generated by a tool. 
	private int x;      // x coordinate in the board
	private int y;      // y coordinate in the board
	private int state;  //  1 if occupied by the user player
                            // -1 if occupied by the computer player
                            //  0 if empty
        
        /**
         * Constructor. Creates a Point object.
         * 
         * @param xt     x coordinate
         * @param yt     y coordinate
         * @param statet state of the point
         */

	Point(int xt, int yt, int statet) {
		x = xt;
		y = yt;
		state = statet;
	}

        /**
         * Tests if two points are equal.
         * 
         * @param q  point to test against
         * @return
         */
        public boolean equalsPosition(Point q) {
		return x==q.x && y==q.y;
	}
	
        /**
         * Sets x coordinate of the point
         * @param x 
         */
        public void setX(int x) {
		this.x = x;
	}
	
        /**
         * Sets y coordinate of the point
         * @param y
         */
        public void setY(int y) {
		this.y = y;
	}

        /**
         * Sets the state of the point
         * @param player
         */
        public void setState(int player) {
		state = player;
	}
	
        /**
         * 
         * @return  x coordinate of the point
         */
        public int getX() {
		return this.x;
	}
	
        /**
         * 
         * @return  y coordinate of the point
         */
        public int getY() {
		return this.y;
	}

        /**
         * 
         * @return the state of the point
         */
        public int getState() {
		return state;
	}
	
	public String toString() {
		return x + "," + y + "|" + state;
	}
	
}
